Todo List
tiagoit/mv-js-04-todo-list pull request #1
Opened 2019-12-19 20:17 UTC by ferreirati

Implemented a todo list using Vanilla JS:
- Modules
- Classes
- Static classes
- Router simulation (SPA Single Page Application)
- uuid NPM library
- webpack
- Bootstrap

2019-12-19 23:31 UTC, bellom reviewed
Reviewing !

2019-12-19 23:32 UTC, bellom reviewed
.

2019-12-19 23:38 UTC, bellom reviewed
.

2019-12-19 23:54 UTC, bellom requested changes
**Hi Team,**
**Great job :+1:  setting up the project :slightly_smiling_face: 

We still have some features to work on;
For some reason your app still lack some important features.
Kindly work on the following; 
#### Interface ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))


#### To-do item / Task ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/todo_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))

When i open your app, am unable to add todo to the project created, and there's no `edit button` and `delete button` for todo. 
checkout the screenshot from your webpage.
![image](https://user-images.githubusercontent.com/31897434/71217948-f142b480-22bf-11ea-8498-fa957c60c624.png)


**Kindly watch and listening carefully to the video and audio code review below;**

https://www.loom.com/share/4327d7fe06684c648d039b51765be326

**_Hope it helps clarify the issues we are having ......_**

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**


Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2019-12-19 23:54 UTC, bellom commented on src/app.service.js
> +
kindly remove this function, we have no logic inside.

2019-12-19 23:54 UTC, bellom commented on src/framework.js
> +  /**
**Kindly remove commented code, you can always use git history to access previous code right :slightly_smiling_face: **

2019-12-20 14:59 UTC, ferreirati commented
Hi @bellom, I guess eslint auto-fix may have broken the toy, working on it now.

2019-12-20 18:07 UTC, BalintMendli approved these changes
Hi @ferreirati @AndresFMoya ,

The app now works as expected. 👏 

It is a 👍 from me.

You can go ahead and merge the project.

2019-12-20 19:32 UTC, merged